import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Vectorize Chat Quickstart",
  description: "Generated by Vectorize",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="sticky top-0 z-50 bg-gray-900 p-4 border-b border-gray-800">
          <div className="max-w-3xl mx-auto flex gap-6">
            <a href="https://thnkandgrow.com" className="text-gray-300 hover:text-white transition-colors">
              Home
            </a>
            <a href="https://blog.thnkandgrow.com" className="text-gray-300 hover:text-white transition-colors">
              Blog
            </a>
            <a href="https://thnkandgrow.com/about" className="text-gray-300 hover:text-white transition-colors">
              About
            </a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
